name: UHCRun
version: 1.0
main: fr.timeuh.uhcrun.UHCRun
authors: [ Timeuh ]
load: STARTUP
description: Un plugin de d'UHC run classique

commands:
  test:
    description: commande de test
    permission: test.use
    aliases: [tst]

  gamebroadcast:
    description: broadcast de partie
    permission: gamebroadcast.use
    aliases: [gbc, gamebc]

  spawn:
    description: retour au spawn

  gamestop:
    description: arrete la partie
    permission: gamestop.use
    aliases: [gstp]

  gamestart:
    description: commence la partie
    permission: gamestart.use
    aliases: [gstt]
