name: UHCRun
version: 2.0
main: fr.timeuh.UHCRun
load: STARTUP
authors: [ Timeuh ]
description: V2 de l'UHC Run

commands:
  start:
    description: commence la partie
    permission: start.use

  gstop:
    description: arrête la partie
    permission: gstop.use

  setState:
    description: change le state actuel du jeu (pour dev seulement)
    permission: setState.use
    aliases: [ss]

  scenario:
    description: affiche les scenarios activés
    aliases: [ses]

  help:
    description: affiche un aide pour le plugin

  commandHelp:
    description: affiche une aide avec la liste des commandes
    aliases: [ch]

  scenarioHelp:
    description: affiche une aide pour la liste de scenarios
    aliases: [sh]
