name: UHCRun
version: 1.0
main: fr.timeuh.uhcrun.UHCRun
authors: [ Timeuh ]
load: STARTUP
description: Un plugin de d'UHC run classique

commands:
  test:
    description: commande de test
    permission: test.use

  broadcast:
    description: broadcast de partie
    permission: gamebroadcast.use
    aliases: [bc]

  spawn:
    description: retour au spawn

  gamestop:
    description: arrete la partie
    permission: gamestop.use
    aliases: [stop]

  start:
    description: commence la partie
    permission: start.use
