name: Timeuh
version: 2.0
main: fr.timeuh.Timeuh
load: STARTUP
authors: [ Timeuh ]
description: V2 de l'UHC Run

commands:
  start:
    description: commence la partie
    permission: start.use

  gstop:
    description: arrete la partie
    permission: gstop.use

  setState:
    description: change le state actuel du jeu (pour dev seulement)
    permission: setState.use
    aliases: [ss]
